title: DASH LAB
author: Simon Woo
email: swoo@g.skku.edu
url: "https://DASH-Lab.github.io"
baseurl: ""
description:  # this means to ignore newlines until "baseurl:"
  Developing Usable and Secure Technology after Better Understanding Data, Machines, and Humans

twitter_username: none
github_username:  DASH-Lab

